// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelScan() {
  return window['go']['main']['App']['CancelScan']();
}

export function CheckSYNPermission() {
  return window['go']['main']['App']['CheckSYNPermission']();
}

export function ScanPorts(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ScanPorts'](arg1, arg2, arg3, arg4, arg5);
}
