// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelScan():Promise<void>;

export function CheckSYNPermission():Promise<boolean>;

export function ScanPorts(arg1:string,arg2:string,arg3:boolean,arg4:number,arg5:number):Promise<string>;
